name: "ll_project"
type: "python:3.10"

dependencies:
    python3:
        pip: "*"

relationships:
    database: "db:postgresql"

variables:
    env:
        DJANGO_SETTINGS_MODULE: 'll_project.settings'

web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

disk: 512

mounts:
    "logs":
        source: local
        source_path: logs

hooks:
    build: |
        pip install --upgrade pip
        pip install psycopg==3.2.3
        pip install gunicorn
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        
        mkdir logs
        python manage.py collectstatic --noinput
        rm -rf logs
    deploy: |
        python manage.py migrate