name: "ll_project"
type: "python:3.10"

relationships:
    database: "db:postgresql"

variables:
    env:
        DJANGO_SETTINGS_MODULE: 'll_project.settings'
        DEBUG: 'False'

web:
    upstream:
        socket_family: unix
    commands:
        start: "python -m gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

disk: 512

mounts:
    "logs":
        source: local
        source_path: logs

hooks:
    build: |
        set -e
        pip install --upgrade pip setuptools wheel
        
        # Install dependencies with verbose output
        pip install -v psycopg[binary]==3.2.3
        pip install -v gunicorn==21.2.0
        
        # Install other requirements
        pip install -r requirements.txt
        pip install -r requirements_remote.txt
        
        # Debug: Show what's installed
        pip list | grep -E "(psycopg|gunicorn)"
        python -c "import psycopg; print('psycopg imported successfully')"
        python -c "import gunicorn; print('gunicorn imported successfully')"
        
        mkdir -p logs
        python manage.py collectstatic --noinput
    deploy: |
        python manage.py migrate