name: "ll_project"
type: "python:3.10"

relationships:
    database: "db:postgresql:13"

# The configuration of the app when it's exposed to the web.
web:
    upstream:
        socket_family: unix
    commands:
        start: "SOCKET=/tmp/app.sock gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
    locations:
        "/":
            # Ensure this matches your Django STATIC_ROOT setting
            root: "static"
        "/static":
            root: "static"
            expires: 1h
            allow: true

# SOCKET environment variable is set inline in the start command below

# The size of the persistent disk of the application (in MB).
disk: 512

# Set a local read/write mount for logs.
mounts:
    "logs":
        source: local
        source_path: logs

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
        apt-get update
        apt-get install -y build-essential libpq-dev
        pip install --upgrade pip
        pip install -r requirements.txt

        mkdir logs
        DJANGO_SETTINGS_MODULE=ll_project.settings python manage.py collectstatic
        rm -rf logs
        python manage.py migrate