name: "ll_project"
type: "python:3.10"

relationships:
    database: "db:postgresql"

variables:
    env:
        DJANGO_SETTINGS_MODULE: 'll_project.settings'
        PIP_INDEX_URL: 'https://pypi.org/simple/'
        PIP_TRUSTED_HOST: 'pypi.org'

web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "static"
            expires: 1h
            allow: true

disk: 512

mounts:
    "logs":
        source: local
        source_path: logs

hooks:
    build: |
        pip install --upgrade pip
        pip install --index-url https://pypi.org/simple/ --trusted-host pypi.org psycopg2-binary==2.9.9
        pip install --index-url https://pypi.org/simple/ --trusted-host pypi.org gunicorn==21.2.0
        pip install -r requirements.txt
        mkdir -p logs
        python manage.py collectstatic --noinput
    deploy: |
        python manage.py migrate